---
- name: Install NVIDIA drivers - CUDA 12
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git, build-essential, libxml2
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - build-essential
        - libxml2
    - name: Download CUDA keyring
      get_url:
        url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb"
        dest: "/tmp/cuda-keyring_1.1-1_all.deb"

    - name: Install CUDA keyring
      apt:
        deb: "/tmp/cuda-keyring_1.1-1_all.deb"

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install CUDA Toolkit 12.3
      apt:
        name: cuda-toolkit-12-3
        state: present

    - name: Install CUDA drivers
      apt:
        name: cuda-drivers
        state: present

    - name: Get installed linux-headers packages
      command: "dpkg-query -f='${binary:Package}\n' -W 'linux-headers*' | grep '^linux-headers' | sort -V"
      register: headers_packages
      changed_when: false

    - name: Install linux-headers for all kernels
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ headers_packages.stdout_lines }}"
