---
- name: Install NVIDIA drivers
  hosts: localhost
  become: true

  vars:
    cuda_url: "https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git, build-essential, libxml2
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - build-essential
        - libxml2

    - name: Install Linux headers
      apt:
        name: linux-headers-{{ ansible_kernel }}
        state: present

    - name: Download CUDA installer
      get_url:
        url: "{{ cuda_url }}"
        dest: /tmp/installer.run

    - name: Run CUDA installer
      command: sh /tmp/installer.run --silent
      args:
        chdir: /tmp

    - name: Remove CUDA installer
      file:
        path: /tmp/installer.run
        state: absent

