---
- name: Install NVIDIA drivers - CUDA 11
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git, build-essential, libxml2
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - build-essential
        - libxml2

    - name: Scarica il file CUDA pin
      get_url:
        url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin"
        dest: "/etc/apt/preferences.d/cuda-repository-pin-600"

    - name: Aggiungi la chiave GPG di NVIDIA
      apt_key:
        url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub"
        state: present

    - name: Aggiungi il repository CUDA
      apt_repository:
        repo: "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
        state: present

    - name: Aggiorna la cache del repository
      apt:
        update_cache: yes

    - name: Installa il pacchetto CUDA
      apt:
        name: cuda
        state: present
        update_cache: yes

    - name: Ottieni la lista dei kernel installati
      shell: "dpkg -l |grep linux-image |cut -d \" \" -f 3|sed -e 's/linux-image/linux-headers/'"
      register: installed_kernels

    - name: Installa gli headers del kernel
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ installed_kernels.stdout_lines }}"
