---
- name: Install NVIDIA drivers
  hosts: localhost
  become: true

  vars:
    cuda_url: "https://developer.download.nvidia.com/compute/cuda/12.3.1/local_installers/cuda_12.3.1_545.23.08_linux.run"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git, build-essential, libxml2
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - build-essential
        - libxml2

    - name: Install Linux headers
      apt:
        name: linux-headers-{{ ansible_kernel }}
        state: present

    - name: Get the last installed kernel header
      shell: dpkg -l | awk '/^ii/ && /linux-headers-/{print $2}' | sort -r | head -n 1
      register: last_kernel_header
      changed_when: false  # Non segnare come "changed" anche se il comando è eseguito

    - name: Download CUDA installer
      get_url:
        url: "{{ cuda_url }}"
        dest: /tmp/installer.run

    - name: Run CUDA installer
      command: sh /tmp/installer.run --silent --kernel-source-path=/usr/src/"{{ last_kernel_header  }}"
      args:
        chdir: /tmp

    - name: Remove CUDA installer
      file:
        path: /tmp/installer.run
        state: absent

