---
- name: Install NVIDIA drivers
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Git, build-essential, libxml2
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - build-essential
        - libxml2

    - name: Install Linux headers
      apt:
        name: linux-headers-{{ ansible_kernel }}
        state: present

    - name: Download CUDA installer
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/12.3.1/local_installers/cuda_12.3.1_545.23.08_linux.run
        dest: /tmp/cuda_12.3.1_545.23.08_linux.run

    - name: Run CUDA installer
      command: sh /tmp/cuda_12.3.1_545.23.08_linux.run --silent
      args:
        chdir: /tmp

