---
- name: Install Docker and deploy Open WebUI
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Installazione driver NVIDIA
    - name: Add NVIDIA GPU repository
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        state: present

    - name: Install NVIDIA drivers and CUDA toolkit
      apt:
        name:
          - nvidia-driver-535
          - nvidia-cuda-toolkit
        state: present

    - name: Install NVIDIA Container Toolkit repository
      apt_repository:
        repo: deb https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/$(ARCH) /
        state: present

    - name: Install NVIDIA Container Toolkit
      apt:
        name:
          - nvidia-container-toolkit
        state: present

    - name: Configure Docker daemon for NVIDIA runtime
      copy:
        content: |
          {
            "default-runtime": "nvidia",
            "runtimes": {
              "nvidia": {
                "path": "nvidia-container-runtime",
                "runtimeArgs": []
              }
            }
          }
        dest: /etc/docker/daemon.json

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Create Docker volumes
      docker_volume:
        name: "{{ item }}"
        state: present
      loop:
        - ollama
        - open-webui

    - name: Run Open WebUI container
      docker_container:
        name: open-webui
        image: ghcr.io/open-webui/open-webui:ollama
        state: started
        restart_policy: always
        ports:
          - "3000:8080"
        volumes:
          - "ollama:/root/.ollama"
          - "open-webui:/app/backend/data"
        devices:
          - "/dev/nvidia0:/dev/nvidia0"
          - "/dev/nvidiactl:/dev/nvidiactl"
          - "/dev/nvidia-uvm:/dev/nvidia-uvm"
        env:
          NVIDIA_VISIBLE_DEVICES: all
