---
- name: Pull and deploy Open WebUI configuration for Ubuntu 24.04
  hosts: localhost
  become: true
  tasks:
    - name: Add architecture support
      shell: dpkg --add-architecture amd64
      
    - name: Install required packages
      apt:
        name:
          - git
          - ansible
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository for Noble (24.04)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present
        filename: docker

    - name: Create directory for configuration
      file:
        path: /opt/openwebui
        state: directory
        mode: '0755'

    - name: Download configuration file
      get_url:
        url: https://raw.githubusercontent.com/Seeweb/cookbooks/refs/heads/main/gpu/openwebui_docker.yaml
        dest: /opt/openwebui/docker-compose.yaml
        mode: '0644'

    - name: Install Docker and Docker Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install NVIDIA repository and GPG key
      block:
        - name: Add NVIDIA GPG key
          apt_key:
            url: https://nvidia.github.io/nvidia-docker/gpgkey
            state: present

        - name: Add NVIDIA repository
          apt_repository:
            repo: deb https://nvidia.github.io/nvidia-docker/ubuntu24.04/amd64 /
            state: present
            filename: nvidia-docker

    - name: Install NVIDIA Container Toolkit
      apt:
        name:
          - nvidia-container-toolkit
          - nvidia-container-runtime
        state: present
        update_cache: yes

    - name: Configure Docker daemon for NVIDIA
      copy:
        content: |
          {
            "default-runtime": "nvidia",
            "runtimes": {
              "nvidia": {
                "path": "nvidia-container-runtime",
                "runtimeArgs": []
              }
            }
          }
        dest: /etc/docker/daemon.json

    - name: Ensure Docker service is running
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Deploy using Docker Compose
      community.docker.docker_compose:
        project_src: /opt/openwebui
        files:
          - docker-compose.yaml
        pull: yes
        state: present
