---
- name: Install K3s
  hosts: all
  become: yes 

  tasks:
    - name: Install K3s using script
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s 

    - name: Retrieve K3s cluster token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Display K3s cluster token
      debug:
        var: k3s_token.stdout_lines
