---
- name: Install MicroK8s on Ubuntu
  hosts: all
  become: true
  tasks:
  - name: Update system
    apt:
      update_cache: yes
      upgrade: dist
  - name: Add Snap repository
    apt_repository:
      repo: ppa:snapcore/ppa
      state: present
  - name: Install snapd
    apt:
      name: snapd
      state: present
  - name: Install MicroK8s
    snap:
      name: microk8s
      channel: latest/stable
