---
- name: Install NVIDIA drivers
  hosts: localhost
  #hosts: gpu
  become: true

  vars:
    nvidia_version: "535"
    kernel_version: "linux-image-nvidia-5.19"
    headers_version: "linux-headers-5.19.0-1014-nvidia"

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Remove Nvidia Graphics Drivers PPA
      ansible.builtin.apt_repository:
        repo: "ppa:graphics-drivers/ppa"
        state: absent

    - name: "Install Nvidia driver version {{ nvidia_version }}"
      ansible.builtin.apt:
        name: nvidia-driver-{{ nvidia_version }}
        state: present

    - name: "Install Linux image {{ kernel_version }}"
      ansible.builtin.apt:
        name: {{ kernel_version }}
        state: present

    - name: "Install Linux headers {{ headers_version }}"
      ansible.builtin.apt:
        name: {{ headers_version }}
        state: present

    
#    - name: Reboot the system
#      ansible.builtin.reboot:
#        reboot_timeout: 300
#        test_command: uptime
#        connect_timeout: 10
#        msg: "Reboot initiated by Ansible"
#      become: true
