---
- name: Install NVIDIA Container Toolkit on Ubuntu 22.04
  hosts: all
  become: true
  tasks:

    - name: Add NVIDIA package repository key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        state: present

    - name: Add NVIDIA package repository
      copy:
        content: |
          deb https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/$(ARCH) /
        dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      apt:
        name:
          - nvidia-container-toolkit
        state: present

    - name: Restart container runtime (e.g., Docker)
      shell: |
        if systemctl is-active --quiet docker; then
          systemctl restart docker
        fi
      args:
        warn: false

    - name: Verify NVIDIA Container Toolkit installation
      command: nvidia-container-cli --version
      register: toolkit_version
      failed_when: toolkit_version.rc != 0

    - name: Show NVIDIA Container Toolkit version
      debug:
        msg: "NVIDIA Container Toolkit version installed: {{ toolkit_version.stdout }}"
