---
- name: Setup Nvidia Container Toolkit package repository and GPG key [Ubuntu]
  ansible.builtin.shell:
    cmd: |
      distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
            && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
            && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
                  sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
                  sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: Install Nvidia Container Toolkit [Ubuntu]
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
    update_cache: true
    autoclean: true
    autoremove: true
