---
- hosts: localhost
  become: true

  tasks: 
    - name: Add Nvidia Container Toolkit GPG key and repository [Ubuntu]
      ansible.builtin.shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && \
        curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list
      register: add_repo

    - name: Install Nvidia Container Toolkit [Ubuntu]
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        state: present
        update_cache: true
        autoclean: true
        autoremove: true
        cache_valid_time: 3600  # Cache is valid for 1 hour
      when: add_repo is succeeded

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true  
